# Generated by Django 2.0.4 on 2018-04-08 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Au', 'Austria'), ('En', 'England'), ('Fr', 'France'), ('Ge', 'Germany'), ('It', 'Italy'), ('Ru', 'Russia'), ('Tu', 'Turkey')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('hold', 'hold'), ('move', 'move'), ('support', 'support'), ('convoy', 'convoy'), ('disband', 'disband'), ('create', 'create')], max_length=7)),
                ('coast', models.CharField(blank=True, choices=[('NC', 'north'), ('EC', 'east'), ('SC', 'south')], max_length=2)),
                ('aux_order_type', models.CharField(choices=[('hold', 'hold'), ('move', 'move')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('abbreviation', models.CharField(max_length=3)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(default=1901)),
                ('season', models.CharField(choices=[('S', 'spring'), ('F', 'fall')], max_length=1)),
                ('phase', models.CharField(choices=[('diplomatic', 'diplomatic'), ('retreat', 'retreat'), ('reinforcement', 'reinforcement')], max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('unit_type', models.CharField(choices=[('A', 'army'), ('F', 'fleet')], max_length=1)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Country')),
            ],
        ),
        migrations.AddField(
            model_name='territory',
            name='unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Unit'),
        ),
        migrations.AddField(
            model_name='order',
            name='aux_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Territory'),
        ),
        migrations.AddField(
            model_name='order',
            name='aux_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Unit'),
        ),
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Territory'),
        ),
        migrations.AddField(
            model_name='order',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Turn'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Unit'),
        ),
        migrations.AddField(
            model_name='country',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
        migrations.AddField(
            model_name='country',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
